Repository nbcamp-archive/kkuk-ios, pull requests merged in 2023-10, with the labels that each got.

#15 [PR] feature/KK-12
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Extension/UIColor.swift
  Kkuk/Resource/Assets.xcassets/Colors/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/background.colorset/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/main.colorset/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/subgray1.colorset/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/subgray2.colorset/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/subgray3.colorset/Contents.json
  Kkuk/Resource/Assets.xcassets/Colors/text1.colorset/Contents.json
Labels: enhancement

#14 [PR] feature/KK-13
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Extension/UIFont+FontSizes.swift
  Kkuk/Resource/Font/Pretendard-Bold.otf
  Kkuk/Resource/Font/Pretendard-Light.otf
  Kkuk/Resource/Font/Pretendard-Medium.otf
  Kkuk/Resource/Font/Pretendard-Regular.otf
  Kkuk/Resource/Font/Pretendard-SemiBold.otf
  Kkuk/Resource/Info.plist
Labels: enhancement

#23 [PR] design/KK-17
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/AddContent/Component/.gitkeep
  Kkuk/Presentation/AddContent/Component/AddContentButton.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: design

#26 [PR] design/KK-19
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/SearchContent/Component/.gitkeep
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: design

#24 [PR] design/KK-18
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/Home/Component/.gitkeep
  Kkuk/Presentation/Home/Component/RecommendPagingView.swift
  Kkuk/Presentation/Home/Component/RecommendView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Resource/Assets.xcassets/Plus.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/Plus.imageset/Plus@1x.png
  Kkuk/Resource/Assets.xcassets/Plus.imageset/Plus@2x.png
  Kkuk/Resource/Assets.xcassets/Plus.imageset/Plus@3x.png
Labels: design

#25 [PR] design/KK-21
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Resource/Assets.xcassets/CategoryView/blueCircle.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/blueCircle.imageset/blue-circle.svg
Labels: design

#39 [PR] design/KK-33
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Core/Model/.gitkeep
  Kkuk/Core/Model/RecentSearchManager.swift
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement, design

#42 [PR]design/KK- 29
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/Component/AddCategoryView.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Resource/Assets.xcassets/CategoryView/animal.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/animal.imageset/animal.svg
  Kkuk/Resource/Assets.xcassets/CategoryView/cafe.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/cafe.imageset/cafe.svg
  Kkuk/Resource/Assets.xcassets/CategoryView/education.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/education.imageset/education.svg
  Kkuk/Resource/Assets.xcassets/CategoryView/plant.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/plant.imageset/plant.svg
  Kkuk/Resource/Assets.xcassets/CategoryView/trip.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/CategoryView/trip.imageset/trip.svg
Labels: design

#38 [PR] design/KK-31
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/AppInfo/Component/.gitkeep
  Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift
  Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift
  Kkuk/Presentation/Home/Component/EmptyStateView.swift
  Kkuk/Presentation/Home/Component/RecommendPagingView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Resource/Assets.xcassets/empty.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/empty.imageset/undraw_No_data_re_kwbl__1_-removebg-preview (1) 1@1x.pdf
Labels: design

#43 [PR] design/KK-28
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Application/AppTabBarController.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/Component/.gitkeep
  Kkuk/Presentation/Category/Component/AddCategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/Component/CategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
Labels: design

#47 [PR] design/KK-45
  Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift
  Kkuk/Presentation/Home/Component/EmptyStateView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Resource/Assets.xcassets/empty.imageset/empty.pdf
Labels: design

#51 [PR] feature/KK-46
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Application/AppTabBarController.swift
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Presentation/Web/Component/WebViewToolbar.swift
  Kkuk/Presentation/Web/View/WebViewController.swift
  Kkuk/Resource/Assets.xcassets/NavigationBar/Contents.json
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_any.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_any@2x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_any@3x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_dark.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_dark@2x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_chevron_left.imageset/lucide_chevron_left_dark@3x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_any.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_any@2x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_any@3x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_dark.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_dark@2x.png
  Kkuk/Resource/Assets.xcassets/NavigationBar/lucide_rotate.imageset/lucide_rotate_dark@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/Contents.json
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_any.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_any@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_any@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_dark.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_dark@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_left_arrow.imageset/lucide_left_arrow_dark@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_any.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_any@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_any@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_dark.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_dark@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_right_arrow.imageset/lucide_right_arrow_dark@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_any.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_any@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_any@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_dark.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_dark@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_safari.imageset/lucide_safari_dark@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_any.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_any@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_any@3x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_dark.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_dark@2x.png
  Kkuk/Resource/Assets.xcassets/WebView/lucide_share.imageset/lucide_share_dark@3x.png
Labels: enhancement

#57 [PR] design/KK-48
  Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift
  Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift
Labels: design

#54 [PR] feature/KK-49
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Core/Manager/ContentManager.swift
  Kkuk/Core/Model/ContentModel.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
Labels: enhancement

#58 [PR] feature/KK-56
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Core/Model/Category.swift
  Kkuk/Presentation/Category/Component/CategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Service/RealmCategoryService.swift
Labels: enhancement

#66 [PR] basic/KK-60
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Component/CompleteButton.swift
  Kkuk/Global/Component/InduceLabel.swift
  Kkuk/Presentation/AddContent/Component/SetCategoryCell.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Resource/Assets.xcassets/Colors/text1.colorset/Contents.json
Labels: enhancement, maintenance

#62 [PR] feature/KK-61
  Kkuk/Application/AppDelegate.swift
  Kkuk/Core/Manager/ContentManager.swift
  Kkuk/Core/Model/ContentModel.swift
  Kkuk/Presentation/Category/Component/CategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Service/RealmCategoryService.swift
Labels: enhancement

#65 [PR] feature/KK-64
  Kkuk/Core/Manager/ContentManager.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement

#68 [PR] feature/KK-67
  Kkuk/Core/Model/ContentModel.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: enhancement

#70 [PR] design/KK-59
  Kkuk/Core/Manager/ContentManager.swift
  Kkuk/Presentation/Home/Component/RecommendPagingView.swift
  Kkuk/Presentation/Home/Component/RecommendView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Resource/Assets.xcassets/Pin.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/Pin.imageset/Pin.pdf
  Kkuk/Resource/Assets.xcassets/selectedPin.imageset/Contents.json
  Kkuk/Resource/Assets.xcassets/selectedPin.imageset/selectedPin.pdf
Labels: enhancement

#71 [PR] Basic/KK-60
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Component/Toast.swift
  Kkuk/Presentation/AddContent/Component/AddContentButton.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
Labels: maintenance

#72 [PR] design/KK-61
  Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift
Labels: design
