Repository nbcamp-archive/kkuk-ios, pull requests merged in 2023-11, with the labels that each got.

#79 [PR] feature/KK-50
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement

#82 [PR] design/KK-78
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: design

#83 [PR] design/KK-76
  Kkuk/Presentation/AppInfo/Component/SettingItemCell.swift
  Kkuk/Presentation/AppInfo/View/AppInfoViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
Labels: design

#84 [PR] design/KK-77
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/Category/Component/AddCategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/Component/CategoryCollectionViewCell.swift
  Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
Labels: design

#81 [PR] design/KK-73
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Component/CompleteButton.swift
  Kkuk/Global/Component/OptionalLabel.swift
  Kkuk/Presentation/AddContent/Component/AddContentButton.swift
  Kkuk/Presentation/AddContent/Component/SelectCategoryCell.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
Labels: design, maintenance

#97 [PR] design/KK-79
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/baby.imageset/Baby.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/baby.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/beauty.imageset/Beauty (2).svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/beauty.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/blueCircle.imageset/blue-circle.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/book.imageset/Book.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/book.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/car.imageset/Car.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/car.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/culture.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/culture.imageset/Culture.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/exercise.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/exercise.imageset/Exercise.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/fashion.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/fashion.imageset/Fashion (1).svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/finance.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/finance.imageset/Finance.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/food.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/food.imageset/Soup.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/health.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/health.imageset/Health.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/interier.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/interier.imageset/Interier.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/it.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/it.imageset/IT.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/kitchen.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/kitchen.imageset/Kitchen (2).svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/music.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/music.imageset/Music.svg
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/shopping.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/CategoryView/shopping.imageset/Shoping.svg
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
Labels: design

#98 [PR] feature/KK-90
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Component/CompleteButton.swift
  Kkuk/Global/Component/OptionalLabel.swift
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_any.png
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_any@2x.png
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_any@3x.png
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_dark.png
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_dark@2x.png
  Kkuk/Global/Resource/Assets.xcassets/AddContentView/lucide_folder_plus.imageset/lucide_folder_plus_dark@3x.png
  Kkuk/Presentation/AddContent/Component/RedirectAddCategoryButton.swift
  Kkuk/Presentation/AddContent/Component/SelectCategoryCell.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: enhancement

#101 [PR] feature/KK-87
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Resource/Assets.xcassets/emptyBoard.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/emptyBoard.imageset/emptyBoard.pdf
  Kkuk/Presentation/Home/Component/EmptyStateView.swift
  Kkuk/Presentation/Home/Component/RecommendPagingView.swift
  Kkuk/Presentation/Home/Component/RecommendView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
Labels: enhancement

#109 [PR] feature/KK-80
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Domain/Helper/ContentHelper.swift
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/Enum/SegmentMenu.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement, design

#110 [PR] design/KK-89
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/Pin.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/Pin.imageset/Pin.pdf
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/more_vertical.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/more_vertical.imageset/more-vertical.png
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/more_vertical.imageset/more-vertical@2x.png
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/more_vertical.imageset/more-vertical@3x.png
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/selectedPin.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/ContentCell/selectedPin.imageset/selectedPin.pdf
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement, design

#124 [PR] feature/KK-116
  .swiftlint.yml
  Kkuk/Application/AppTabBarController.swift
  Kkuk/Global/Enum/AppTabBarItem.swift
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_any.png
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_any@2x.png
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_any@3x.png
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_dark.png
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_dark@2x.png
  Kkuk/Global/Resource/Assets.xcassets/AppTabBarItem/lucide_plus_action.imageset/lucide_plus_action_dark@3x.png
  Kkuk/Global/Resource/Assets.xcassets/Colors/main.colorset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/Colors/subgray3.colorset/Contents.json
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: enhancement, maintenance

#127 [PR] feature/KK-125
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: enhancement

#128 [PR] feature/KK-126
  Kkuk.xcodeproj/project.pbxproj
  Kkuk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kkuk/Global/Resource/Settings.bundle/LicenseProject.latest_result.txt
  Kkuk/Global/Resource/Settings.bundle/LicenseProject.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/Alamofire.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/IQKeyboardManager.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/Kingfisher.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/PanModal.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/SnapKit.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/SwiftSoup.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/realm-core.plist
  Kkuk/Global/Resource/Settings.bundle/LicenseProject/realm-swift.plist
  Kkuk/Global/Resource/Settings.bundle/Root.plist
  Kkuk/Global/Resource/Settings.bundle/en.lproj/Root.strings
Labels: enhancement

#121 [PR]feature/KK-100
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Home/Component/BookmarkCell.swift
  Kkuk/Presentation/Home/Component/RecommendPagingView.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/Component/ContentTableViewCell.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: bug, enhancement

#131 [PR] design/KK-115
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift
  Kkuk/Presentation/Setting/Component/SettingItemCell.swift
  Kkuk/Presentation/Setting/View/SettingViewController.swift
Labels: design

#130 [PR]design/KK-122
  Kkuk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Presentation/Category/View/EditCategoryViewController.swift
  Kkuk/Presentation/Category/View/PanModalTableViewController.swift
Labels: design

#133 [PR] refactor/KK-132
  Kkuk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift
  Kkuk/Presentation/Category/View/EditCategoryViewController.swift
Labels: bug

#135 [PR] feature/KK-117
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Domain/Helper/CategoryHelper.swift
  Kkuk/Domain/Helper/ContentHelper.swift
  Kkuk/Global/Base/BaseUIViewController.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Content/ContentTableViewCell.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/PanModal/Enum/PanModalOption.swift
  Kkuk/Presentation/PanModal/PanModalTableViewCell.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement

#138 [PR] feature/KK-134
  Kkuk/Global/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Kkuk/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/KKUK.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/KKUK.imageset/KKUK.png
  Kkuk/Global/Resource/LaunchScreen.storyboard
  Kkuk/Presentation/Setting/View/SettingViewController.swift
Labels: enhancement

#146 [PR] feature/KK-141
  Kkuk/Application/SceneDelegate.swift
Labels: enhancement

#147 [PR] refactor/KK-144
  Kkuk/Presentation/Home/Component/BookmarkCell.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
Labels: bug

#148 [PR] feature/KK-127
  Kkuk/Domain/Helper/CategoryHelper.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
  Kkuk/Presentation/Setting/View/SettingViewController.swift
Labels: enhancement

#152 [PR] refactor/KK-120
  .swiftlint.yml
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Global/Resource/Assets.xcassets/AddCategoryView/uncategorized.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/AddCategoryView/uncategorized.imageset/Uncategorized.svg
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
Labels: maintenance

#153 [PR] design/KK-140
  Kkuk.xcodeproj/project.pbxproj
  Kkuk/Global/Base/BaseUIViewController.swift
  Kkuk/Global/Enum/Asset.swift
  Kkuk/Global/Extension/UITextField+CustomTextField.swift
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/Component/AddCategoryIconCollectionViewCell.swift
  Kkuk/Presentation/Category/Component/CategoryTableViewCell.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Presentation/Category/View/EditCategoryViewController.swift
  Kkuk/Presentation/Home/Component/BookmarkCell.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
  Kkuk/Presentation/Setting/View/SettingViewController.swift
  Kkuk/Presentation/Web/View/WebViewController.swift
Labels: enhancement, design

#154 [PK]refactor/KK-145
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: bug

#161 [PR] refactor/KK-160
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
Labels: bug

#159 [PR] design/KK-158
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Category/View/CategoryViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
Labels: design

#170 [PR] refactor/KK-166
  Kkuk/Application/SceneDelegate.swift
  Kkuk/Domain/Helper/ContentHelper.swift
  Kkuk/Global/Resource/Settings.bundle/Root.plist
  Kkuk/Global/Resource/Settings.bundle/en.lproj/Root.strings
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  KkukShareExtension/View/AddContentShareViewController.swift
Labels: enhancement, maintenance

#171 [PR] design/KK-167
  Kkuk/Presentation/Category/Component/AddCategoryIconCollectionViewCell.swift
Labels: design

#172 [PR] design/KK-163
  Kkuk/Domain/Helper/ContentHelper.swift
  Kkuk/Global/Resource/Assets.xcassets/SearchView/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x (1).png
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x (2).png
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x.png
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
Labels: enhancement, design

#176 [PR] feature/KK-165
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
Labels: enhancement

#174 [PR] feature/KK-173
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/PanModal/PanModalTableViewCell.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
Labels: enhancement

#177 [PR] 1.2
  Kkuk/Application/SceneDelegate.swift
  Kkuk/Domain/Helper/ContentHelper.swift
  Kkuk/Global/Resource/Assets.xcassets/SearchView/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/Contents.json
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x (1).png
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x (2).png
  Kkuk/Global/Resource/Assets.xcassets/SearchView/x_mark.imageset/x.png
  Kkuk/Global/Resource/Settings.bundle/Root.plist
  Kkuk/Global/Resource/Settings.bundle/en.lproj/Root.strings
  Kkuk/Presentation/AddContent/View/AddContentViewController.swift
  Kkuk/Presentation/Category/Component/AddCategoryIconCollectionViewCell.swift
  Kkuk/Presentation/Category/View/AddCategoryViewController.swift
  Kkuk/Presentation/Category/View/CategoryInnerViewController.swift
  Kkuk/Presentation/Home/View/HomeViewController.swift
  Kkuk/Presentation/PanModal/PanModalTableViewCell.swift
  Kkuk/Presentation/PanModal/PanModalTableViewController.swift
  Kkuk/Presentation/SearchContent/Component/RecentSearchContentCollectionViewCell.swift
  Kkuk/Presentation/SearchContent/View/RecentSearchContentViewController.swift
  Kkuk/Presentation/SearchContent/View/SearchContentViewController.swift
  KkukShareExtension/View/AddContentShareViewController.swift
Labels: enhancement, maintenance
